export ZSH=$HOME/.oh-my-zsh

export TERM=xterm-256color

export EDITOR=vim
export PAGER="less -FRXS"

export HOMEBREW_NO_INSECURE_REDIRECT=1
export HOMEBREW_NO_ANALYTICS=1

export HOMEBREW_BUNDLE_NO_LOCK=true

export GOPATH=$HOME/go

